{
 "title": "MonApp",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Position in stock (tons)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "monapp_position_in_stock", "legendFormat": "{{ position }}" }
   ]
  },
  {
   "title": "Min. in Stock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(monapp_position_in_stock[1h])",
     "legendFormat": "{{position}}"
    }
   ]
  },
  {
   "title": "Avg. in Stock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(monapp_position_in_stock[1h])",
     "legendFormat": "{{position}}"
    }
   ]
  },
  {
   "title": "Max. in Stock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(monapp_position_in_stock[1h])",
     "legendFormat": "{{position}}"
    }
   ]
  },
  {
   "title": "All Alerts Info",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "labelSelector": "*", "legendFormat": "{{ summary }}", "target": "Query", "type": "table" },
    { "labelSelector": "*", "legendFormat": "{{ instance }}", "target": "Query", "type": "table" }
   ]
  }
 ]
}